import JSZip from 'jszip';
import { Project } from '../types';

export async function exportProjectAsZip(project: Project): Promise<void> {
  const zip = new JSZip();

  // 1. Add all project files with proper folder structure
  for (const file of project.files) {
    // Clean leading slash if any
    const relativePath = file.path.startsWith('/') ? file.path.slice(1) : file.path;
    zip.file(relativePath, file.content);
  }

  // 2. Ensure README exists with actual run instructions
  const hasReadme = project.files.some(
    (f) => f.path.toLowerCase().endsWith('readme.md')
  );

  if (!hasReadme) {
    const readmeContent = `# ${project.name}

> Generated by **KiranIA — AI Operating System**
> Created on: ${new Date(project.createdAt).toLocaleString()}

## Description
${project.description || 'Production-ready software project built with KiranIA.'}

## Project Structure
\`\`\`
${project.files.map((f) => f.path).join('\n')}
\`\`\`

## Getting Started
1. Unzip this package into your local workspace.
2. If this project contains a \`package.json\`:
   \`\`\`bash
   npm install
   npm run dev
   \`\`\`
3. If this project contains static HTML files:
   Open \`index.html\` directly in any modern web browser or run:
   \`\`\`bash
   npx serve .
   \`\`\`

## Architecture & Verification
- Project Type: ${project.type || 'Web Application'}
- Verified with KiranIA Code Engine.
`;
    zip.file('README.md', readmeContent);
  }

  // 3. Generate binary blob
  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });

  // 4. Trigger browser download
  const sanitizedName = (project.name || 'kiranai-project')
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '-');
  const filename = `${sanitizedName}.zip`;

  const downloadUrl = URL.createObjectURL(zipBlob);
  const anchor = document.createElement('a');
  anchor.href = downloadUrl;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);

  setTimeout(() => {
    URL.revokeObjectURL(downloadUrl);
  }, 1000);
}
